import type { Domain, Entity, EntityKind, PlayerId } from "./types.ts";
type Spec = Omit<Entity, "id" | "ownerId" | "x" | "y" | "state" | "order" | "queue" | "blueprint" | "alive" | "harvestreadyat" | "repairprogress" | "footprint" | "domain" | "attackDomains">;
const specs: Record<EntityKind, Spec> = {
  hq: { kind: "hq", hp: 1200, hpmax: 1200, armor: "structure", radius_cells: 2.2, movespeed: 0, visionrange: 8, attackrange: 0, attackdamage: 0, damageClass: "none", attackperiod: 0, attackreadyat: 0, cargo: 0, cargocapacity: 0 }, processor: { kind: "processor", hp: 650, hpmax: 650, armor: "structure", radius_cells: 1.5, movespeed: 0, visionrange: 7, attackrange: 0, attackdamage: 0, damageClass: "none", attackperiod: 0, attackreadyat: 0, cargo: 0, cargocapacity: 0 }, assembly: { kind: "assembly", hp: 750, hpmax: 750, armor: "structure", radius_cells: 1.5, movespeed: 0, visionrange: 7, attackrange: 0, attackdamage: 0, damageClass: "none", attackperiod: 0, attackreadyat: 0, cargo: 0, cargocapacity: 0, production: "vehicle" }, "infantry-center": { kind: "infantry-center", hp: 500, hpmax: 500, armor: "structure", radius_cells: 1, movespeed: 0, visionrange: 7, attackrange: 0, attackdamage: 0, damageClass: "none", attackperiod: 0, attackreadyat: 0, cargo: 0, cargocapacity: 0, production: "infantry" }, mcv: { kind: "mcv", hp: 700, hpmax: 700, armor: "heavy", radius_cells: .65, movespeed: 2, visionrange: 7, attackrange: 0, attackdamage: 0, damageClass: "none", attackperiod: 0, attackreadyat: 0, cargo: 0, cargocapacity: 0 }, harvester: { kind: "harvester", hp: 300, hpmax: 300, armor: "light", radius_cells: .52, movespeed: 3.5, visionrange: 6, attackrange: 0, attackdamage: 0, damageClass: "none", attackperiod: 0, attackreadyat: 0, cargo: 0, cargocapacity: 200 }, scout: { kind: "scout", hp: 260, hpmax: 260, armor: "light", radius_cells: .42, movespeed: 7, visionrange: 9, attackrange: 5.5, attackdamage: 24, damageClass: "autocannon", attackperiod: 24, attackreadyat: 0, cargo: 0, cargocapacity: 0 }, infantry: { kind: "infantry", hp: 180, hpmax: 180, armor: "personnel", radius_cells: .22, movespeed: 3, visionrange: 6.5, attackrange: 4.5, attackdamage: 22, damageClass: "rifle", attackperiod: 30, attackreadyat: 0, cargo: 0, cargocapacity: 0 }, tank: { kind: "tank", hp: 520, hpmax: 520, armor: "heavy", radius_cells: .55, movespeed: 2.4, visionrange: 7, attackrange: 6, attackdamage: 82, damageClass: "explosive", attackperiod: 72, attackreadyat: 0, cargo: 0, cargocapacity: 0 }, "anti-tank": { kind: "anti-tank", hp: 230, hpmax: 230, armor: "personnel", radius_cells: .32, movespeed: 2.7, visionrange: 7, attackrange: 7.5, attackdamage: 105, damageClass: "anti-armor", attackperiod: 90, attackreadyat: 0, cargo: 0, cargocapacity: 0 }, "air-support": { kind: "air-support", hp: 420, hpmax: 420, armor: "light", radius_cells: .48, movespeed: 6, visionrange: 8, attackrange: 5, attackdamage: 42, damageClass: "explosive", attackperiod: 36, attackreadyat: 0, cargo: 0, cargocapacity: 0 }, "naval-support": { kind: "naval-support", hp: 520, hpmax: 520, armor: "heavy", radius_cells: .52, movespeed: 4, visionrange: 8, attackrange: 7, attackdamage: 70, damageClass: "anti-armor", attackperiod: 45, attackreadyat: 0, cargo: 0, cargocapacity: 0 },
};
export type Recipe = { product: EntityKind; producer: "vehicle" | "infantry"; producerKind: "assembly" | "infantry-center"; cost: number; ticks: number };
export const RECIPES: Record<string, Recipe> = { "recipe.v1.lynx-scout-car": { product: "scout", producer: "vehicle", producerKind: "assembly", cost: 300, ticks: 90 }, "recipe.v1.line-rifle": { product: "infantry", producer: "infantry", producerKind: "infantry-center", cost: 100, ticks: 45 }, "recipe.v1.valiant-mbt": { product: "tank", producer: "vehicle", producerKind: "assembly", cost: 750, ticks: 210 }, "recipe.v1.javelin-team": { product: "anti-tank", producer: "infantry", producerKind: "infantry-center", cost: 240, ticks: 90 }, "recipe.v1.harvester": { product: "harvester", producer: "vehicle", producerKind: "assembly", cost: 700, ticks: 180 }, "recipe.v1.mcv": { product: "mcv", producer: "vehicle", producerKind: "assembly", cost: 1200, ticks: 420 } };
export const V1_RECIPES = new Set(Object.keys(RECIPES));
export function entityDomain(kind: EntityKind): Domain { return kind === "air-support" ? "air" : kind === "naval-support" ? "naval" : "ground"; }
export function attackDomains(kind: EntityKind): Domain[] { return kind === "air-support" ? ["ground"] : kind === "naval-support" ? ["air", "naval"] : ["ground"]; }
export function makeEntity(ownerId: PlayerId, kind: EntityKind, x: number, y: number, id: number): Entity { const s = specs[kind]; const footprint = kind === "hq" ? { width_cells: 4, height_cells: 4 } : kind === "processor" || kind === "assembly" ? { width_cells: 3, height_cells: 3 } : kind === "infantry-center" ? { width_cells: 2, height_cells: 2 } : { width_cells: 1, height_cells: 1 }; return { ...s, id, ownerId, kind, x, y, state: "idle", queue: [], alive: true, cargocapacity: s.cargocapacity, harvestreadyat: 0, repairprogress: 0, footprint, domain: entityDomain(kind), attackDomains: attackDomains(kind) }; }
export function isCombat(kind: EntityKind): boolean { return ["scout", "infantry", "tank", "anti-tank", "air-support", "naval-support"].includes(kind); }
export function isGroundCombat(kind: EntityKind): boolean { return ["scout", "infantry", "tank", "anti-tank"].includes(kind); }
export function canAttack(attacker: Entity, target: Entity): boolean { return (attacker.attackDomains ?? attackDomains(attacker.kind)).includes(target.domain ?? entityDomain(target.kind)); }
