import { RECIPES, V1_RECIPES, canAttack, isCombat, isGroundCombat, makeEntity } from "./content.ts";
import { loadV1Manifest } from "../content/index.ts";
import type { ContentManifest } from "../content/index.ts";
import { HEIGHT, WIDTH, distance, isBuildable } from "./map.ts";
import type { Command, CommandResult, Entity, Event, GameView, Intel, PlayerId, SimulationState } from "./types.ts";

const HZ = 30;
const players: PlayerId[] = [1, 2];
const sides = { west: 1 as PlayerId, east: 2 as PlayerId };
const emptyIntel = (): Intel => ({ discovered: Array(WIDTH * HEIGHT).fill(false), lastSeen: {} });

function newState(seed: bigint, manifest: ContentManifest, waterRegion?: SimulationState["waterRegion"]): SimulationState {
  const { scenario, map } = manifest;
  return { scenarioId: "scenario.v1-meridian-crossing", seed, tick: 0, phase: "running", result: { winnerId: null, reason: null }, nextEntityId: 1, nextEventId: 1, resources: { 1: { banked: scenario.startingResources.banked, reserved: scenario.startingResources.reserved }, 2: { banked: scenario.startingResources.banked, reserved: scenario.startingResources.reserved } }, entities: [], nodes: map.resourceNodes.map((node, index) => ({ id: index + 1, x: node.point[0], y: node.point[1], reserve: node.reserve, occupiedBy: null })), objective: { x: map.objective.point[0], y: map.objective.point[1], capture_radius_cells: map.objective.captureRadiusCells, no_build_radius_cells: map.objective.noBuildRadiusCells, progress: 0, ownerId: null, holdTicks: { 1: 0, 2: 0 }, captureRemainder: 0 }, acceptedCommands: [], events: [], commandResults: { 1: [], 2: [] }, lastSequence: { 1: -1, 2: -1 }, intel: { 1: emptyIntel(), 2: emptyIntel() }, ...(waterRegion ? { waterRegion } : {}) };
}

export type SimulationOptions = { includeSupport?: boolean };
export function createSimulationFromManifest(manifest: ContentManifest, seed?: bigint, options: SimulationOptions = {}): Simulation {
  const sim = new Simulation(newState(seed ?? manifest.scenario.seed, manifest, options.includeSupport ? { minX: 12, maxX: 52, minY: 33, maxY: 37 } : undefined), manifest);
  const spawnKinds: Record<string, Entity["kind"]> = { hq: "hq", processor: "processor", assembly: "assembly", mcv: "mcv", harvester: "harvester", scout: "scout", infantry: "infantry", tank: "tank", anti_tank: "anti-tank" };
  const spawns = [...manifest.scenario.spawns].sort((a, b) => a.creationOrder - b.creationOrder);
  for (const side of ["west", "east"] as const) { const owner = sides[side]; for (const spawn of spawns) { const kind = spawnKinds[spawn.key]; if (kind) { const position = side === "west" ? spawn.westPosition : spawn.eastPosition; sim.spawn(owner, kind, { x: position[0], y: position[1] }); } } if (options.includeSupport) { sim.spawn(owner, "air-support", { x: owner === 1 ? 16 : 48, y: 15 }); sim.spawn(owner, "naval-support", { x: owner === 1 ? 16 : 48, y: 35 }); } }
  sim.updateIntel();
  return sim;
}
export function createSimulation(seed?: bigint, options: SimulationOptions = {}): Simulation {
  const manifest = loadV1Manifest();
  return createSimulationFromManifest(manifest, seed, options);
}

export function createSupportSimulation(seed = 0x56315f4d45524944n): Simulation { return createSimulation(seed, { includeSupport: true }); }

export class Simulation {
  readonly state: SimulationState;
  readonly manifest: ContentManifest;
  constructor(state: SimulationState, manifest: ContentManifest = loadV1Manifest()) { this.state = state; this.manifest = manifest; }
  spawn(ownerId: PlayerId, kind: Entity["kind"], point: { x: number; y: number }): Entity { const e = makeEntity(ownerId, kind, point.x, point.y, this.state.nextEntityId++); this.state.entities.push(e); return e; }
  entity(id: number): Entity | undefined { return this.state.entities.find(e => e.id === id && e.alive); }
  private emit(kind: string, entityIds: number[], data?: Event["data"]): void { this.state.events.push({ id: this.state.nextEventId++, tick: this.state.tick, kind, entityIds: [...entityIds].sort((a, b) => a - b), data }); }

  submit(c: Command): CommandResult {
    const p = c.playerId as PlayerId; let result: CommandResult;
    if (!players.includes(p) || c.sequence <= (this.state.lastSequence[p] ?? -1) || c.applyAtTick <= this.state.tick) result = { sequence: c.sequence, accepted: false, reason: "stale" };
    else if (this.state.phase !== "running" || !Number.isInteger(c.sequence) || !Number.isInteger(c.applyAtTick) || !Array.isArray(c.subjectIds) || c.subjectIds.length === 0 || c.subjectIds.length > 16 || new Set(c.subjectIds).size !== c.subjectIds.length) result = { sequence: c.sequence, accepted: false, reason: "malformed" };
    else { const subjects = c.subjectIds.map(id => this.entity(id)); result = subjects.some(e => !e) ? { sequence: c.sequence, accepted: false, reason: "invalid-subject" } : subjects.some(e => e!.ownerId !== p) ? { sequence: c.sequence, accepted: false, reason: "not-owner" } : this.validate(c, subjects as Entity[]); }
    if (players.includes(p)) this.state.lastSequence[p] = Math.max(this.state.lastSequence[p], c.sequence);
    this.state.commandResults[p]?.push(result);
    if (result.accepted) this.state.acceptedCommands.push({ ...c, subjectIds: [...c.subjectIds].sort((a, b) => a - b) }); else this.emit("command-rejected", [], { sequence: c.sequence, reason: result.reason ?? "malformed" });
    return result;
  }

  private validate(c: Command, subjects: Entity[]): CommandResult {
    if (c.kind === "move") return c.point && subjects.every(e => e.movespeed > 0) ? (subjects.every(e => this.canMoveTo(e, c.point!)) ? { sequence: c.sequence, accepted: true } : { sequence: c.sequence, accepted: false, reason: "blocked" }) : { sequence: c.sequence, accepted: false, reason: "invalid-subject" };
    if (c.kind === "stop") return { sequence: c.sequence, accepted: true };
    if (c.kind === "attack") {
      if (subjects.some(e => !isCombat(e.kind)) || (!c.targetId && !c.point)) return { sequence: c.sequence, accepted: false, reason: "invalid-target" };
      if (c.targetId) { const target = this.entity(c.targetId); if (!target || target.ownerId === subjects[0].ownerId || subjects.some(e => !canAttack(e, target))) return { sequence: c.sequence, accepted: false, reason: "invalid-target" }; if (subjects.some(e => !this.canSee(e.ownerId, target))) return { sequence: c.sequence, accepted: false, reason: "not-visible" }; }
      return { sequence: c.sequence, accepted: true };
    }
    if (c.kind === "harvest") { const node = c.targetId && this.state.nodes.find(n => n.id === c.targetId); if (subjects.length !== 1 || subjects[0].kind !== "harvester" || !node) return { sequence: c.sequence, accepted: false, reason: "invalid-target" }; if (node.occupiedBy !== null && node.occupiedBy !== subjects[0].id) return { sequence: c.sequence, accepted: false, reason: "blocked" }; return { sequence: c.sequence, accepted: true }; }
    if (c.kind === "capture") return c.targetId === 1 && subjects.every(e => isGroundCombat(e.kind)) ? { sequence: c.sequence, accepted: true } : { sequence: c.sequence, accepted: false, reason: "invalid-target" };
    if (c.kind === "produce") { const r = c.recipeId && RECIPES[c.recipeId]; const producer = subjects[0]; if (!r || !V1_RECIPES.has(c.recipeId!) || subjects.length !== 1 || producer.kind !== r.producerKind || producer.production !== r.producer) return { sequence: c.sequence, accepted: false, reason: "unavailable" }; if (producer.queue.length >= 8) return { sequence: c.sequence, accepted: false, reason: "queue-full" }; if (this.state.resources[producer.ownerId].banked < r.cost) return { sequence: c.sequence, accepted: false, reason: "insufficient-resource" }; return { sequence: c.sequence, accepted: true }; }
    if (c.kind === "construct") { const b = subjects[0]; const hq = this.state.entities.find(e => e.ownerId === b.ownerId && e.kind === "hq" && e.alive); const occupied = this.state.entities.filter(e => e.alive).map(e => ({ x: Math.floor(e.x), y: Math.floor(e.y) })); if (subjects.length !== 1 || b.kind !== "mcv" || b.blueprint || c.recipeId !== "recipe.v1.infantry-center" || !c.point || !isBuildable(c.point.x, c.point.y, this.state.nodes, occupied) || (distance(b, c.point) > 10 && (!hq || distance(hq, c.point) > 12))) return { sequence: c.sequence, accepted: false, reason: "blocked" }; if (this.state.resources[b.ownerId].banked < 400) return { sequence: c.sequence, accepted: false, reason: "insufficient-resource" }; return { sequence: c.sequence, accepted: true }; }
    return { sequence: c.sequence, accepted: false, reason: "unsupported-in-scenario" };
  }

  step(ticks = 1): void { for (let i = 0; i < ticks && this.state.phase === "running"; i++) this.tick(); }
  private tick(): void { this.state.tick++; for (const c of this.state.acceptedCommands.filter(c => c.applyAtTick === this.state.tick)) this.apply(c); this.produce(); this.construct(); this.orders(); this.harvest(); this.combat(); this.objective(); this.cleanup(); this.checkResult(); this.updateIntel(); }
  private apply(c: Command): void {
    for (const id of c.subjectIds) { const e = this.entity(id); if (!e) continue; if (c.kind === "stop") { this.releaseNode(e); e.order = undefined; e.blueprint = undefined; e.state = "idle"; } else if (c.kind === "move" && c.point) { this.releaseNode(e); e.order = { kind: "move", x: c.point.x, y: c.point.y }; e.state = "moving"; } else if (c.kind === "attack") e.order = { kind: "attack", targetId: c.targetId, x: c.point?.x, y: c.point?.y }; else if (c.kind === "harvest" && c.targetId) { const n = this.state.nodes.find(n => n.id === c.targetId)!; n.occupiedBy = e.id; e.order = { kind: "harvest", nodeId: c.targetId, harvestStage: "to-node" }; e.state = "harvesting"; } else if (c.kind === "capture") { e.order = { kind: "move", x: this.state.objective.x, y: this.state.objective.y }; e.state = "moving"; } }
    if (c.kind === "produce") { const p = this.entity(c.subjectIds[0]); const r = c.recipeId && RECIPES[c.recipeId]; if (p && r) { this.state.resources[p.ownerId].banked -= r.cost; this.state.resources[p.ownerId].reserved += r.cost; p.queue.push({ recipeId: c.recipeId!, product: r.product, remaining: r.ticks, cost: r.cost }); } }
    if (c.kind === "construct") { const b = this.entity(c.subjectIds[0]); if (b && c.point) { this.state.resources[b.ownerId].banked -= 400; this.state.resources[b.ownerId].reserved += 400; b.blueprint = { product: "infantry-center", x: Math.floor(c.point.x), y: Math.floor(c.point.y), progress: 0, cost: 400, builderId: b.id }; b.order = { kind: "construct", x: Math.floor(c.point.x), y: Math.floor(c.point.y) }; b.state = "constructing"; } }
  }
  private orders(): void { for (const e of this.state.entities.filter(e => e.alive && e.order && !e.blueprint)) { const o = e.order!; if (o.kind === "move") this.moveEntity(e, o.x!, o.y!); else if (o.kind === "attack" && o.targetId) { const t = this.entity(o.targetId); if (t && distance(e, t) > e.attackrange * .9 && e.movespeed > 0) this.moveEntity(e, t.x, t.y); } } }
  private canMoveTo(e: Entity, point: { x: number; y: number }): boolean { if (point.x < 0 || point.x >= WIDTH || point.y < 0 || point.y >= HEIGHT) return false; return e.domain !== "naval" && e.domain !== "air" || (!!this.state.waterRegion && e.domain === "naval" && point.x >= this.state.waterRegion.minX && point.x <= this.state.waterRegion.maxX && point.y >= this.state.waterRegion.minY && point.y <= this.state.waterRegion.maxY) || e.domain === "air"; }
  private moveEntity(e: Entity, x: number, y: number): void { const d = distance(e, { x, y }); if (d <= .25) { e.x = x; e.y = y; e.state = "idle"; return; } const step = Math.min(e.movespeed / HZ, d); const next = { x: e.x + (x - e.x) / d * step, y: e.y + (y - e.y) / d * step }; if (!this.canMoveTo(e, next)) { e.order = undefined; e.state = "idle"; this.emit(e.domain === "naval" ? "naval-route-blocked" : "route-blocked", [e.id]); return; } e.x = next.x; e.y = next.y; e.state = "moving"; }
  private construct(): void { for (const e of this.state.entities.filter(e => e.alive && e.blueprint)) { const b = e.blueprint!; if (distance(e, b) > 1) { this.moveEntity(e, b.x, b.y); continue; } e.state = "constructing"; b.progress++; if (b.progress < 240) continue; this.state.resources[e.ownerId].reserved -= b.cost; const built = this.spawn(e.ownerId, "infantry-center", { x: b.x, y: b.y }); e.blueprint = undefined; e.order = undefined; e.state = "idle"; this.emit("construction-complete", [e.id, built.id]); } }
  private produce(): void { for (const p of this.state.entities.filter(e => e.alive && e.production)) { const item = p.queue[0]; if (!item) continue; item.remaining--; if (item.remaining > 0) continue; p.queue.shift(); this.state.resources[p.ownerId].reserved -= item.cost; const x = p.kind === "infantry-center" ? (p.ownerId === 1 ? p.x + 2 : p.x - 2) : (p.ownerId === 1 ? p.x + 3 : p.x - 3); const unit = this.spawn(p.ownerId, item.product, { x, y: p.y }); this.emit("production-complete", [p.id, unit.id]); } }
  private harvest(): void { for (const e of this.state.entities.filter(e => e.alive && e.kind === "harvester" && e.order?.kind === "harvest")) { const o = e.order!; const n = this.state.nodes.find(n => n.id === o.nodeId); const p = this.state.entities.find(p => p.ownerId === e.ownerId && p.kind === "processor" && p.alive); if (!n || !p) continue; if (o.harvestStage === "to-node") { if (distance(e, n) <= 1.2) { o.harvestStage = "harvesting"; e.harvestreadyat = this.state.tick + 30; } else this.moveEntity(e, n.x, n.y); } else if (o.harvestStage === "harvesting") { e.state = "harvesting"; if (this.state.tick >= e.harvestreadyat) { const amount = Math.min(20, e.cargocapacity - e.cargo, n.reserve); e.cargo += amount; n.reserve -= amount; e.harvestreadyat = this.state.tick + 30; } if (e.cargo >= e.cargocapacity || n.reserve === 0) { o.harvestStage = "to-processor"; n.occupiedBy = null; } } else if (o.harvestStage === "to-processor") { if (distance(e, p) <= 1.7) o.harvestStage = "unloading"; else this.moveEntity(e, p.x, p.y); } else { e.state = "unloading"; const amount = Math.min(40, e.cargo); e.cargo -= amount; this.state.resources[e.ownerId].banked += amount; if (e.cargo === 0) { if (n.reserve > 0) { n.occupiedBy = e.id; o.harvestStage = "to-node"; e.harvestreadyat = this.state.tick + 30; } else { e.order = undefined; e.state = "idle"; } } } } }
  private combat(): void { const ratios: Record<string, Record<string, number>> = { rifle: { personnel: 1, light: .35, heavy: .05, structure: .05 }, autocannon: { personnel: 1.2, light: .8, heavy: .25, structure: .1 }, "anti-armor": { personnel: .45, light: 1, heavy: 1.1, structure: .7 }, explosive: { personnel: 1, light: .85, heavy: .65, structure: .75 } }; for (const a of this.state.entities.filter(e => e.alive && isCombat(e.kind))) { const t = a.order?.kind === "attack" && a.order.targetId ? this.entity(a.order.targetId) : undefined; if (!t || t.ownerId === a.ownerId || !canAttack(a, t) || distance(a, t) > a.attackrange || this.state.tick < a.attackreadyat) continue; a.attackreadyat = this.state.tick + a.attackperiod; const damage = Math.max(1, Math.floor(a.attackdamage * (ratios[a.damageClass]?.[t.armor] ?? 1))); t.hp = Math.max(0, t.hp - damage); this.emit("damage", [a.id, t.id], { amount: damage }); } }
  private objective(): void { const count: Record<PlayerId, number> = { 1: 0, 2: 0 }; for (const e of this.state.entities.filter(e => e.alive && isGroundCombat(e.kind) && distance(e, this.state.objective) <= this.state.objective.capture_radius_cells)) count[e.ownerId] = Math.min(3, count[e.ownerId] + 1); if (count[1] && count[2]) return; const strength = count[1] || -count[2]; if (strength) { this.state.objective.captureRemainder += strength; while (this.state.objective.captureRemainder >= 6) { this.state.objective.progress = Math.min(100, this.state.objective.progress + 1); this.state.objective.captureRemainder -= 6; } while (this.state.objective.captureRemainder <= -6) { this.state.objective.progress = Math.max(-100, this.state.objective.progress - 1); this.state.objective.captureRemainder += 6; } } else if (this.state.objective.progress !== 0) { this.state.objective.captureRemainder += this.state.objective.progress > 0 ? -1 : 1; while (this.state.objective.captureRemainder <= -12) { this.state.objective.progress++; this.state.objective.captureRemainder += 12; } while (this.state.objective.captureRemainder >= 12) { this.state.objective.progress--; this.state.objective.captureRemainder -= 12; } } this.state.objective.ownerId = this.state.objective.progress === 100 ? 1 : this.state.objective.progress === -100 ? 2 : null; if (this.state.objective.ownerId) { const p = this.state.objective.ownerId; this.state.objective.holdTicks[p]++; if (this.state.tick % 5 === 0) this.state.resources[p].banked++; } }
  private cleanup(): void { for (const e of this.state.entities) if (e.alive && e.hp <= 0) { this.releaseNode(e); e.alive = false; e.state = "destroyed"; e.order = undefined; this.emit("destroyed", [e.id]); } }
  private checkResult(): void { for (const p of players) if (!this.state.entities.some(e => e.ownerId === p && e.kind === "hq" && e.alive)) { this.state.phase = "victory"; this.state.result = { winnerId: p === 1 ? 2 : 1, reason: "hq-destroyed" }; return; } for (const p of players) if (this.state.objective.holdTicks[p] >= this.manifest.scenario.objectiveHoldSeconds * HZ) { this.state.phase = "victory"; this.state.result = { winnerId: p, reason: "objective-held" }; return; } }
  private releaseNode(e: Entity): void { for (const n of this.state.nodes) if (n.occupiedBy === e.id) n.occupiedBy = null; }
  private canSee(playerId: PlayerId, target: Entity): boolean { return target.ownerId === playerId || this.state.entities.some(e => e.alive && e.ownerId === playerId && distance(e, target) <= e.visionrange); }
  updateIntel(): void { for (const p of players) { const intel = this.state.intel[p]; for (const o of this.state.entities.filter(e => e.alive && e.ownerId === p)) { const minX = Math.max(0, Math.floor(o.x - o.visionrange)); const maxX = Math.min(WIDTH - 1, Math.floor(o.x + o.visionrange)); const minY = Math.max(0, Math.floor(o.y - o.visionrange)); const maxY = Math.min(HEIGHT - 1, Math.floor(o.y + o.visionrange)); for (let y = minY; y <= maxY; y++) for (let x = minX; x <= maxX; x++) if (distance(o, { x: x + .5, y: y + .5 }) <= o.visionrange) intel.discovered[y * WIDTH + x] = true; } for (const e of this.state.entities.filter(e => e.alive && e.ownerId !== p && this.canSee(p, e))) intel.lastSeen[e.id] = { x: e.x, y: e.y, kind: e.kind, tick: this.state.tick }; } }
  view(playerId: PlayerId): GameView { this.updateIntel(); const visible = this.state.entities.filter(e => e.alive && (e.ownerId === playerId || this.canSee(playerId, e))); const ids = new Set(visible.map(e => e.id)); const contacts = Object.entries(this.state.intel[playerId].lastSeen).filter(([id]) => !ids.has(Number(id))).map(([id, x]) => ({ id: Number(id), kind: x.kind, x: x.x, y: x.y, stale: true, lastSeenTick: x.tick })); return { schemaVersion: 1, playerId, tick: this.state.tick, phase: this.state.phase, result: this.state.result, resources: { ...this.state.resources[playerId] }, entities: visible.map(e => ({ id: e.id, ownerId: e.ownerId, kind: e.kind, x: e.x, y: e.y, hp: e.hp, hpmax: e.hpmax, state: e.state, cargo: e.cargo, ...(e.ownerId === playerId && e.order ? { order: e.order } : {}) })), contacts, terrain: { width: WIDTH, height: HEIGHT, discoveredCells: this.state.intel[playerId].discovered.map((v, i) => v ? i : -1).filter(i => i >= 0), coverCells: this.coverCells() }, objective: { ...this.state.objective, holdTicks: { ...this.state.objective.holdTicks } }, production: visible.filter(e => e.production).map(e => ({ producerId: e.id, queue: e.queue.map(q => ({ ...q })) })), construction: this.state.entities.filter(e => e.ownerId === playerId && e.blueprint).map(e => ({ builderId: e.id, x: e.blueprint!.x, y: e.blueprint!.y, progress: e.blueprint!.progress, legal: true })), events: this.state.events.filter(e => e.entityIds.length === 0 || e.entityIds.some(id => ids.has(id))).slice(-100), commandResults: this.state.commandResults[playerId].slice(-100) }; }
  private coverCells(): number[] {
    const layers = (this.manifest.map.data as Record<string, unknown> | undefined)?.layers as { cover_rectangles?: { bounds?: number[] }[] } | undefined;
    const cells = new Set<number>();
    for (const rect of layers?.cover_rectangles ?? []) {
      const b = rect.bounds;
      if (!Array.isArray(b) || b.length < 4) continue;
      const [x0, y0, w, h] = b;
      for (let y = y0; y < y0 + h; y++) for (let x = x0; x < x0 + w; x++) if (x >= 0 && x < WIDTH && y >= 0 && y < HEIGHT) cells.add(y * WIDTH + x);
    }
    return [...cells];
  }
}
